using DHBWAutomation.Backend.Core.Models;
using Microsoft.EntityFrameworkCore;

namespace DHBWAutomation.Backend.Core.Services.KnowledgeNetwork;

public partial class KnowledgeNetworkService
{
    /// <summary>
    /// Create a manual link between two entities
    /// </summary>
    public async Task<KnowledgeLink> CreateLinkAsync(
        int? userId,
        string sourceType,
        int sourceId,
        string targetType,
        int targetId,
        string linkType = KnowledgeLinkTypes.Related,
        string? description = null)
    {
        var existing = await _context.KnowledgeLinks
            .FirstOrDefaultAsync(l =>
                l.SourceType == sourceType && l.SourceId == sourceId &&
                l.TargetType == targetType && l.TargetId == targetId);

        if (existing != null)
        {
            _logger.LogDebug("Link already exists between {SourceType}:{SourceId} and {TargetType}:{TargetId}",
                sourceType, sourceId, targetType, targetId);
            return existing;
        }

        var link = new KnowledgeLink
        {
            UserId = userId,
            SourceType = sourceType,
            SourceId = sourceId,
            TargetType = targetType,
            TargetId = targetId,
            LinkType = linkType,
            Description = description,
            Strength = 1.0,
            IsAutoGenerated = false,
            IsConfirmed = true
        };

        _context.KnowledgeLinks.Add(link);
        await _context.SaveChangesAsync();

        _logger.LogInformation("Created link: {SourceType}:{SourceId} -> {TargetType}:{TargetId}",
            sourceType, sourceId, targetType, targetId);

        return link;
    }

    /// <summary>
    /// Delete a link
    /// </summary>
    public async Task<bool> DeleteLinkAsync(int linkId, int? userId = null)
    {
        var link = await _context.KnowledgeLinks.FindAsync(linkId);
        if (link == null) return false;

        if (userId.HasValue && link.UserId != userId)
        {
            _logger.LogWarning("User {UserId} tried to delete link {LinkId} owned by {OwnerId}",
                userId, linkId, link.UserId);
            return false;
        }

        _context.KnowledgeLinks.Remove(link);
        await _context.SaveChangesAsync();

        return true;
    }

    /// <summary>
    /// Get all links for an entity
    /// </summary>
    public async Task<List<KnowledgeLink>> GetLinksForEntityAsync(
        string entityType,
        int entityId,
        int? userId = null)
    {
        var query = _context.KnowledgeLinks
            .Where(l =>
                (l.SourceType == entityType && l.SourceId == entityId) ||
                (l.TargetType == entityType && l.TargetId == entityId && l.IsBidirectional))
            .Where(l => !l.IsRejected);

        if (userId.HasValue)
        {
            query = query.Where(l => l.UserId == null || l.UserId == userId);
        }

        return await query.ToListAsync();
    }

    /// <summary>
    /// Confirm an auto-generated link
    /// </summary>
    public async Task<bool> ConfirmLinkAsync(int linkId, int userId)
    {
        var link = await _context.KnowledgeLinks.FindAsync(linkId);
        if (link == null || link.UserId != userId) return false;

        link.IsConfirmed = true;
        link.UpdatedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();

        return true;
    }

    /// <summary>
    /// Reject an auto-generated link
    /// </summary>
    public async Task<bool> RejectLinkAsync(int linkId, int userId)
    {
        var link = await _context.KnowledgeLinks.FindAsync(linkId);
        if (link == null || link.UserId != userId) return false;

        link.IsRejected = true;
        link.UpdatedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();

        return true;
    }

    /// <summary>
    /// Get pending auto-generated links for user to review
    /// </summary>
    public async Task<List<KnowledgeLink>> GetPendingLinksAsync(int userId)
    {
        return await _context.KnowledgeLinks
            .Where(l => l.UserId == userId &&
                        l.IsAutoGenerated &&
                        !l.IsConfirmed &&
                        !l.IsRejected)
            .OrderByDescending(l => l.VectorSimilarity)
            .Take(10)
            .ToListAsync();
    }

    /// <summary>
    /// Generate automatic links based on semantic similarity
    /// </summary>
    public async Task<int> GenerateSemanticLinksAsync(int? userId = null, double threshold = 0.85)
    {
        var linksCreated = 0;

        try
        {
            var embeddings = await _context.QdrantEmbeddings
                .Where(e => userId == null || e.UserId == userId || e.UserId == null)
                .ToListAsync();

            _logger.LogInformation("Processing {Count} embeddings for auto-linking", embeddings.Count);

            foreach (var embedding in embeddings)
            {
                var similar = await _embeddingService.FindSimilarAsync(
                    embedding.EntityType, embedding.EntityId, userId, topK: 5, threshold: threshold);

                foreach (var match in similar)
                {
                    var exists = await _context.KnowledgeLinks.AnyAsync(l =>
                        (l.SourceType == embedding.EntityType && l.SourceId == embedding.EntityId &&
                         l.TargetType == match.EntityType && l.TargetId == match.EntityId) ||
                        (l.SourceType == match.EntityType && l.SourceId == match.EntityId &&
                         l.TargetType == embedding.EntityType && l.TargetId == embedding.EntityId));

                    if (!exists)
                    {
                        var link = new KnowledgeLink
                        {
                            UserId = userId,
                            SourceType = embedding.EntityType,
                            SourceId = embedding.EntityId,
                            TargetType = match.EntityType,
                            TargetId = match.EntityId,
                            LinkType = KnowledgeLinkTypes.Related,
                            Strength = match.Score,
                            VectorSimilarity = match.Score,
                            IsAutoGenerated = true,
                            IsBidirectional = true
                        };

                        _context.KnowledgeLinks.Add(link);
                        linksCreated++;
                    }
                }
            }

            await _context.SaveChangesAsync();
            _logger.LogInformation("Generated {Count} automatic links", linksCreated);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating semantic links");
        }

        return linksCreated;
    }
}
