namespace DHBWAutomation.Backend.Core.Services.KnowledgeNetwork;

/// <summary>
/// Basic entity info for display
/// </summary>
public class EntityInfo
{
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
}

/// <summary>
/// Related content item
/// </summary>
public class RelatedContentItem
{
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public float Score { get; set; }
    public string LinkType { get; set; } = string.Empty;
    public bool IsExplicitLink { get; set; }
}

/// <summary>
/// Search result item
/// </summary>
public class SearchResultItem
{
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public float Score { get; set; }
}

/// <summary>
/// Network graph for visualization
/// </summary>
public class NetworkGraph
{
    public List<NetworkNode> Nodes { get; set; } = new();
    public List<NetworkEdge> Edges { get; set; } = new();
}

/// <summary>
/// Node in the network graph
/// </summary>
public class NetworkNode
{
    public string Id { get; set; } = string.Empty;
    public string Label { get; set; } = string.Empty;
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
}

/// <summary>
/// Edge in the network graph
/// </summary>
public class NetworkEdge
{
    public string Id { get; set; } = string.Empty;
    public string Source { get; set; } = string.Empty;
    public string Target { get; set; } = string.Empty;
    public string LinkType { get; set; } = string.Empty;
    public double Weight { get; set; }
    public bool IsAutoGenerated { get; set; }
}

/// <summary>
/// Result of indexing operation
/// </summary>
public class IndexingResult
{
    public int DocumentsProcessed { get; set; }
    public int ExercisesProcessed { get; set; }
    public int KnowledgeItemsProcessed { get; set; }
    public int TotalProcessed { get; set; }
    public List<string> Errors { get; set; } = new();
}

/// <summary>
/// Cluster visualization data
/// </summary>
public class ClusterVisualizationData
{
    public bool Success { get; set; }
    public string? Message { get; set; }
    public string Method { get; set; } = "umap";
    public List<ClusterPoint> Points { get; set; } = new();
}

/// <summary>
/// Single point in cluster visualization
/// </summary>
public class ClusterPoint
{
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
    public string Label { get; set; } = string.Empty;
    public double X { get; set; }
    public double Y { get; set; }
    public string Category { get; set; } = string.Empty;
}
