using DHBWAutomation.Backend.Core.Models;
using Microsoft.EntityFrameworkCore;

namespace DHBWAutomation.Backend.Core.Services.KnowledgeNetwork;

public partial class KnowledgeNetworkService
{
    /// <summary>
    /// Get network graph for visualization
    /// </summary>
    public async Task<NetworkGraph> GetNetworkGraphAsync(int? userId = null, int maxNodes = 100)
    {
        var graph = new NetworkGraph();
        var entityKeys = new HashSet<string>();

        var linksQuery = _context.KnowledgeLinks.Where(l => !l.IsRejected);

        if (userId.HasValue)
        {
            linksQuery = linksQuery.Where(l => l.UserId == null || l.UserId == userId);
        }

        var links = await linksQuery.Take(maxNodes * 2).ToListAsync();

        foreach (var link in links)
        {
            var sourceKey = $"{link.SourceType}:{link.SourceId}";
            var targetKey = $"{link.TargetType}:{link.TargetId}";

            if (!entityKeys.Contains(sourceKey))
            {
                entityKeys.Add(sourceKey);
                var info = await GetEntityInfoAsync(link.SourceType, link.SourceId);
                if (info != null)
                {
                    graph.Nodes.Add(new NetworkNode
                    {
                        Id = sourceKey,
                        Label = info.Title,
                        EntityType = link.SourceType,
                        EntityId = link.SourceId
                    });
                }
            }

            if (!entityKeys.Contains(targetKey))
            {
                entityKeys.Add(targetKey);
                var info = await GetEntityInfoAsync(link.TargetType, link.TargetId);
                if (info != null)
                {
                    graph.Nodes.Add(new NetworkNode
                    {
                        Id = targetKey,
                        Label = info.Title,
                        EntityType = link.TargetType,
                        EntityId = link.TargetId
                    });
                }
            }

            graph.Edges.Add(new NetworkEdge
            {
                Id = link.Id.ToString(),
                Source = sourceKey,
                Target = targetKey,
                LinkType = link.LinkType,
                Weight = link.Strength,
                IsAutoGenerated = link.IsAutoGenerated
            });

            if (graph.Nodes.Count >= maxNodes) break;
        }

        return graph;
    }

    /// <summary>
    /// Get cluster visualization data using dimensionality reduction
    /// </summary>
    public async Task<ClusterVisualizationData> GetClusterVisualizationAsync(
        int userId,
        string method = "umap",
        int maxNodes = 200)
    {
        try
        {
            var points = await _qdrantService.GetAllPointsWithVectorsAsync(userId, maxNodes / 5);

            if (points.Count < 3)
            {
                return new ClusterVisualizationData
                {
                    Success = false,
                    Message = $"Not enough data for clustering (found {points.Count}, minimum 3 required)"
                };
            }

            _logger.LogInformation("Processing {Count} points for cluster visualization", points.Count);

            var clusterPoints = ProjectTo2D(points);

            foreach (var point in clusterPoints)
            {
                var info = await GetEntityInfoAsync(point.EntityType, point.EntityId);
                if (info != null)
                {
                    point.Label = info.Title;
                }
            }

            return new ClusterVisualizationData
            {
                Success = true,
                Method = method,
                Points = clusterPoints,
                Message = $"Successfully generated {clusterPoints.Count} cluster points"
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating cluster visualization");
            return new ClusterVisualizationData
            {
                Success = false,
                Message = ex.Message
            };
        }
    }
}
