using DHBWAutomation.Backend.Core.Models;
using DHBWAutomation.Backend.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;

namespace DHBWAutomation.Backend.Core.Services;

/// <summary>
/// Service for managing the knowledge network ("Spinnennetz")
/// </summary>
public class KnowledgeNetworkService : IKnowledgeNetworkService
{
    private readonly AppDbContext _context;
    private readonly IEmbeddingService _embeddingService;
    private readonly ILogger<KnowledgeNetworkService> _logger;

    private const double AutoLinkThreshold = 0.8;

    public KnowledgeNetworkService(
        AppDbContext context,
        IEmbeddingService embeddingService,
        ILogger<KnowledgeNetworkService> logger)
    {
        _context = context;
        _embeddingService = embeddingService;
        _logger = logger;
    }

    /// <summary>
    /// Create a manual link between two entities
    /// </summary>
    public async Task<KnowledgeLink> CreateLinkAsync(
        int? userId,
        string sourceType,
        int sourceId,
        string targetType,
        int targetId,
        string linkType = KnowledgeLinkTypes.Related,
        string? description = null)
    {
        // Check if link already exists
        var existing = await _context.KnowledgeLinks
            .FirstOrDefaultAsync(l =>
                l.SourceType == sourceType && l.SourceId == sourceId &&
                l.TargetType == targetType && l.TargetId == targetId);

        if (existing != null)
        {
            _logger.LogDebug("Link already exists between {SourceType}:{SourceId} and {TargetType}:{TargetId}",
                sourceType, sourceId, targetType, targetId);
            return existing;
        }

        var link = new KnowledgeLink
        {
            UserId = userId,
            SourceType = sourceType,
            SourceId = sourceId,
            TargetType = targetType,
            TargetId = targetId,
            LinkType = linkType,
            Description = description,
            Strength = 1.0,
            IsAutoGenerated = false,
            IsConfirmed = true
        };

        _context.KnowledgeLinks.Add(link);
        await _context.SaveChangesAsync();

        _logger.LogInformation("Created link: {SourceType}:{SourceId} -> {TargetType}:{TargetId}",
            sourceType, sourceId, targetType, targetId);

        return link;
    }

    /// <summary>
    /// Delete a link
    /// </summary>
    public async Task<bool> DeleteLinkAsync(int linkId, int? userId = null)
    {
        var link = await _context.KnowledgeLinks.FindAsync(linkId);
        if (link == null)
        {
            return false;
        }

        if (userId.HasValue && link.UserId != userId)
        {
            _logger.LogWarning("User {UserId} tried to delete link {LinkId} owned by {OwnerId}",
                userId, linkId, link.UserId);
            return false;
        }

        _context.KnowledgeLinks.Remove(link);
        await _context.SaveChangesAsync();

        return true;
    }

    /// <summary>
    /// Get all links for an entity
    /// </summary>
    public async Task<List<KnowledgeLink>> GetLinksForEntityAsync(
        string entityType,
        int entityId,
        int? userId = null)
    {
        var query = _context.KnowledgeLinks
            .Where(l =>
                (l.SourceType == entityType && l.SourceId == entityId) ||
                (l.TargetType == entityType && l.TargetId == entityId && l.IsBidirectional))
            .Where(l => !l.IsRejected);

        if (userId.HasValue)
        {
            query = query.Where(l => l.UserId == null || l.UserId == userId);
        }

        return await query.ToListAsync();
    }

    /// <summary>
    /// Find related content using both explicit links and semantic similarity
    /// </summary>
    public async Task<List<RelatedContentItem>> FindRelatedContentAsync(
        string entityType,
        int entityId,
        int? userId = null,
        int maxResults = 20,
        int depth = 1)
    {
        var results = new List<RelatedContentItem>();
        var visited = new HashSet<string> { $"{entityType}:{entityId}" };

        // 1. Get explicit links
        var explicitLinks = await GetLinksForEntityAsync(entityType, entityId, userId);

        foreach (var link in explicitLinks)
        {
            var relatedType = link.SourceType == entityType && link.SourceId == entityId
                ? link.TargetType
                : link.SourceType;
            var relatedId = link.SourceType == entityType && link.SourceId == entityId
                ? link.TargetId
                : link.SourceId;

            var key = $"{relatedType}:{relatedId}";
            if (visited.Contains(key)) continue;
            visited.Add(key);

            var entityInfo = await GetEntityInfoAsync(relatedType, relatedId);
            if (entityInfo != null)
            {
                results.Add(new RelatedContentItem
                {
                    EntityType = relatedType,
                    EntityId = relatedId,
                    Title = entityInfo.Title,
                    Description = entityInfo.Description,
                    Score = (float)link.Strength,
                    LinkType = link.LinkType,
                    IsExplicitLink = true
                });
            }
        }

        // 2. Get semantically similar content
        var semanticResults = await _embeddingService.FindSimilarAsync(
            entityType, entityId, userId, maxResults, AutoLinkThreshold);

        foreach (var result in semanticResults)
        {
            var key = $"{result.EntityType}:{result.EntityId}";
            if (visited.Contains(key)) continue;
            visited.Add(key);

            var entityInfo = await GetEntityInfoAsync(result.EntityType, result.EntityId);
            if (entityInfo != null)
            {
                results.Add(new RelatedContentItem
                {
                    EntityType = result.EntityType,
                    EntityId = result.EntityId,
                    Title = entityInfo.Title,
                    Description = entityInfo.Description,
                    Score = result.Score,
                    LinkType = KnowledgeLinkTypes.Related,
                    IsExplicitLink = false
                });
            }
        }

        // Sort by score and limit
        return results
            .OrderByDescending(r => r.Score)
            .Take(maxResults)
            .ToList();
    }

    /// <summary>
    /// Generate automatic links based on semantic similarity
    /// </summary>
    public async Task<int> GenerateSemanticLinksAsync(int? userId = null, double threshold = 0.85)
    {
        var linksCreated = 0;

        try
        {
            // Get all entities with embeddings
            var embeddings = await _context.QdrantEmbeddings
                .Where(e => userId == null || e.UserId == userId || e.UserId == null)
                .ToListAsync();

            _logger.LogInformation("Processing {Count} embeddings for auto-linking", embeddings.Count);

            foreach (var embedding in embeddings)
            {
                // Find similar entities
                var similar = await _embeddingService.FindSimilarAsync(
                    embedding.EntityType,
                    embedding.EntityId,
                    userId,
                    topK: 5,
                    threshold: threshold
                );

                foreach (var match in similar)
                {
                    // Check if link already exists
                    var exists = await _context.KnowledgeLinks.AnyAsync(l =>
                        (l.SourceType == embedding.EntityType && l.SourceId == embedding.EntityId &&
                         l.TargetType == match.EntityType && l.TargetId == match.EntityId) ||
                        (l.SourceType == match.EntityType && l.SourceId == match.EntityId &&
                         l.TargetType == embedding.EntityType && l.TargetId == embedding.EntityId));

                    if (!exists)
                    {
                        var link = new KnowledgeLink
                        {
                            UserId = userId,
                            SourceType = embedding.EntityType,
                            SourceId = embedding.EntityId,
                            TargetType = match.EntityType,
                            TargetId = match.EntityId,
                            LinkType = KnowledgeLinkTypes.Related,
                            Strength = match.Score,
                            VectorSimilarity = match.Score,
                            IsAutoGenerated = true,
                            IsBidirectional = true
                        };

                        _context.KnowledgeLinks.Add(link);
                        linksCreated++;
                    }
                }
            }

            await _context.SaveChangesAsync();
            _logger.LogInformation("Generated {Count} automatic links", linksCreated);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating semantic links");
        }

        return linksCreated;
    }

    /// <summary>
    /// Semantic search across all knowledge
    /// </summary>
    public async Task<List<SearchResultItem>> SearchAsync(
        string query,
        int? userId = null,
        int maxResults = 20)
    {
        var results = new List<SearchResultItem>();

        // Semantic search
        var semanticResults = await _embeddingService.SemanticSearchAsync(query, userId, maxResults);

        foreach (var result in semanticResults)
        {
            var entityInfo = await GetEntityInfoAsync(result.EntityType, result.EntityId);
            if (entityInfo != null)
            {
                results.Add(new SearchResultItem
                {
                    EntityType = result.EntityType,
                    EntityId = result.EntityId,
                    Title = entityInfo.Title,
                    Description = entityInfo.Description,
                    Score = result.Score
                });
            }
        }

        return results;
    }

    /// <summary>
    /// Get network graph for visualization
    /// </summary>
    public async Task<NetworkGraph> GetNetworkGraphAsync(int? userId = null, int maxNodes = 100)
    {
        var graph = new NetworkGraph();
        var entityKeys = new HashSet<string>();

        // Get links
        var linksQuery = _context.KnowledgeLinks
            .Where(l => !l.IsRejected);

        if (userId.HasValue)
        {
            linksQuery = linksQuery.Where(l => l.UserId == null || l.UserId == userId);
        }

        var links = await linksQuery.Take(maxNodes * 2).ToListAsync();

        // Build nodes from links
        foreach (var link in links)
        {
            var sourceKey = $"{link.SourceType}:{link.SourceId}";
            var targetKey = $"{link.TargetType}:{link.TargetId}";

            if (!entityKeys.Contains(sourceKey))
            {
                entityKeys.Add(sourceKey);
                var info = await GetEntityInfoAsync(link.SourceType, link.SourceId);
                if (info != null)
                {
                    graph.Nodes.Add(new NetworkNode
                    {
                        Id = sourceKey,
                        Label = info.Title,
                        EntityType = link.SourceType,
                        EntityId = link.SourceId
                    });
                }
            }

            if (!entityKeys.Contains(targetKey))
            {
                entityKeys.Add(targetKey);
                var info = await GetEntityInfoAsync(link.TargetType, link.TargetId);
                if (info != null)
                {
                    graph.Nodes.Add(new NetworkNode
                    {
                        Id = targetKey,
                        Label = info.Title,
                        EntityType = link.TargetType,
                        EntityId = link.TargetId
                    });
                }
            }

            graph.Edges.Add(new NetworkEdge
            {
                Id = link.Id.ToString(),
                Source = sourceKey,
                Target = targetKey,
                LinkType = link.LinkType,
                Weight = link.Strength,
                IsAutoGenerated = link.IsAutoGenerated
            });

            if (graph.Nodes.Count >= maxNodes) break;
        }

        return graph;
    }

    /// <summary>
    /// Confirm an auto-generated link
    /// </summary>
    public async Task<bool> ConfirmLinkAsync(int linkId, int userId)
    {
        var link = await _context.KnowledgeLinks.FindAsync(linkId);
        if (link == null || link.UserId != userId)
        {
            return false;
        }

        link.IsConfirmed = true;
        link.UpdatedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();

        return true;
    }

    /// <summary>
    /// Reject an auto-generated link
    /// </summary>
    public async Task<bool> RejectLinkAsync(int linkId, int userId)
    {
        var link = await _context.KnowledgeLinks.FindAsync(linkId);
        if (link == null || link.UserId != userId)
        {
            return false;
        }

        link.IsRejected = true;
        link.UpdatedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();

        return true;
    }

    /// <summary>
    /// Get pending auto-generated links for user to review
    /// </summary>
    public async Task<List<KnowledgeLink>> GetPendingLinksAsync(int userId)
    {
        return await _context.KnowledgeLinks
            .Where(l => l.UserId == userId &&
                        l.IsAutoGenerated &&
                        !l.IsConfirmed &&
                        !l.IsRejected)
            .OrderByDescending(l => l.VectorSimilarity)
            .Take(10)
            .ToListAsync();
    }

    /// <summary>
    /// Index all existing content for a user (create embeddings)
    /// </summary>
    public async Task<IndexingResult> IndexAllUserContentAsync(int userId)
    {
        var result = new IndexingResult();

        try
        {
            // Process Documents
            var documents = await _context.Documents
                .Where(d => d.UserId == userId && !d.HasEmbedding)
                .ToListAsync();

            _logger.LogInformation("Processing {Count} documents for user {UserId}", documents.Count, userId);

            foreach (var doc in documents)
            {
                try
                {
                    var success = await _embeddingService.ProcessDocumentEmbeddingAsync(doc.Id, userId);
                    if (success)
                    {
                        result.DocumentsProcessed++;
                    }
                    else
                    {
                        result.Errors.Add($"Failed to process document {doc.Id} ({doc.FileName})");
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error processing document {DocumentId}", doc.Id);
                    result.Errors.Add($"Error processing document {doc.Id}: {ex.Message}");
                }
            }

            // Process Exercises (JavaDocsExercises) - global exercises, not user-specific
            var exercises = await _context.JavaDocsExercises
                .Where(e => !e.HasEmbedding)
                .ToListAsync();

            _logger.LogInformation("Processing {Count} exercises without embeddings", exercises.Count);

            foreach (var exercise in exercises)
            {
                try
                {
                    var success = await _embeddingService.ProcessExerciseEmbeddingAsync(exercise.Id);
                    if (success)
                    {
                        result.ExercisesProcessed++;
                    }
                    else
                    {
                        result.Errors.Add($"Failed to process exercise {exercise.Id}");
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error processing exercise {ExerciseId}", exercise.Id);
                    result.Errors.Add($"Error processing exercise {exercise.Id}: {ex.Message}");
                }
            }

            // Process Knowledge Base Items
            var knowledgeItems = await _context.KnowledgeBaseItems
                .Where(k => k.UserId == userId && !k.HasEmbedding)
                .ToListAsync();

            _logger.LogInformation("Processing {Count} knowledge items for user {UserId}", knowledgeItems.Count, userId);

            foreach (var item in knowledgeItems)
            {
                try
                {
                    var success = await _embeddingService.ProcessKnowledgeItemEmbeddingAsync(item.Id, userId);
                    if (success)
                    {
                        result.KnowledgeItemsProcessed++;
                    }
                    else
                    {
                        result.Errors.Add($"Failed to process knowledge item {item.Id}");
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error processing knowledge item {ItemId}", item.Id);
                    result.Errors.Add($"Error processing knowledge item {item.Id}: {ex.Message}");
                }
            }

            result.TotalProcessed = result.DocumentsProcessed + result.ExercisesProcessed + result.KnowledgeItemsProcessed;

            _logger.LogInformation(
                "Indexing completed for user {UserId}: {Total} items processed ({Docs} docs, {Ex} exercises, {KI} knowledge items), {Errors} errors",
                userId, result.TotalProcessed, result.DocumentsProcessed, result.ExercisesProcessed,
                result.KnowledgeItemsProcessed, result.Errors.Count);

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error indexing content for user {UserId}", userId);
            throw;
        }
    }

    private async Task<EntityInfo?> GetEntityInfoAsync(string entityType, int entityId)
    {
        return entityType switch
        {
            KnowledgeEntityTypes.Document => await GetDocumentInfoAsync(entityId),
            KnowledgeEntityTypes.KnowledgeItem => await GetKnowledgeItemInfoAsync(entityId),
            KnowledgeEntityTypes.JavaDocsExercise => await GetExerciseInfoAsync(entityId),
            KnowledgeEntityTypes.Image => await GetImageInfoAsync(entityId),
            KnowledgeEntityTypes.MoodleResource => await GetMoodleResourceInfoAsync(entityId),
            _ => null
        };
    }

    private async Task<EntityInfo?> GetDocumentInfoAsync(int id)
    {
        var doc = await _context.Documents.FindAsync(id);
        return doc == null ? null : new EntityInfo
        {
            Title = doc.FileName,
            Description = doc.Summary ?? doc.Subject
        };
    }

    private async Task<EntityInfo?> GetKnowledgeItemInfoAsync(int id)
    {
        var item = await _context.KnowledgeBaseItems.FindAsync(id);
        return item == null ? null : new EntityInfo
        {
            Title = $"{item.Subject}: {item.Topic}",
            Description = item.Notes
        };
    }

    private async Task<EntityInfo?> GetExerciseInfoAsync(int id)
    {
        var exercise = await _context.JavaDocsExercises.FindAsync(id);
        return exercise == null ? null : new EntityInfo
        {
            Title = exercise.Title,
            Description = $"{exercise.Topic} - {exercise.Difficulty}"
        };
    }

    private async Task<EntityInfo?> GetImageInfoAsync(int id)
    {
        var image = await _context.DocumentImages
            .Include(i => i.Document)
            .FirstOrDefaultAsync(i => i.Id == id);

        return image == null ? null : new EntityInfo
        {
            Title = $"Image from {image.Document.FileName} (Page {image.PageNumber})",
            Description = image.GeminiDescription
        };
    }

    private async Task<EntityInfo?> GetMoodleResourceInfoAsync(int id)
    {
        var resource = await _context.MoodleResources.FindAsync(id);
        return resource == null ? null : new EntityInfo
        {
            Title = resource.Title,
            Description = resource.CourseName
        };
    }

    /// <summary>
    /// Get cluster visualization data using dimensionality reduction
    /// </summary>
    public async Task<ClusterVisualizationData> GetClusterVisualizationAsync(
        int userId,
        string method = "umap",
        int maxNodes = 200)
    {
        try
        {
            // Get all embeddings for user
            var embeddings = await _context.QdrantEmbeddings
                .Where(e => e.UserId == userId || e.UserId == null)
                .Take(maxNodes)
                .ToListAsync();

            if (embeddings.Count < 3)
            {
                return new ClusterVisualizationData
                {
                    Success = false,
                    Message = "Not enough data for clustering (minimum 3 nodes required)"
                };
            }

            // Fetch vectors from Qdrant via QdrantService
            var vectorData = new List<ClusterPoint>();
            foreach (var emb in embeddings)
            {
                // For now, we'll need to store vectors in a way we can retrieve them
                // This is a simplified approach - in production you'd fetch from Qdrant
                _logger.LogWarning("Vector retrieval from Qdrant not yet implemented for clustering");
            }

            // For now, return a mock response
            // TODO: Implement actual dimensionality reduction via Python service
            return new ClusterVisualizationData
            {
                Success = true,
                Method = method,
                Points = new List<ClusterPoint>(),
                Message = "Clustering feature coming soon - requires Python service integration"
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating cluster visualization");
            return new ClusterVisualizationData
            {
                Success = false,
                Message = ex.Message
            };
        }
    }
}

/// <summary>
/// Basic entity info for display
/// </summary>
public class EntityInfo
{
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
}

/// <summary>
/// Related content item
/// </summary>
public class RelatedContentItem
{
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public float Score { get; set; }
    public string LinkType { get; set; } = string.Empty;
    public bool IsExplicitLink { get; set; }
}

/// <summary>
/// Search result item
/// </summary>
public class SearchResultItem
{
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public float Score { get; set; }
}

/// <summary>
/// Network graph for visualization
/// </summary>
public class NetworkGraph
{
    public List<NetworkNode> Nodes { get; set; } = new();
    public List<NetworkEdge> Edges { get; set; } = new();
}

/// <summary>
/// Node in the network graph
/// </summary>
public class NetworkNode
{
    public string Id { get; set; } = string.Empty;
    public string Label { get; set; } = string.Empty;
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
}

/// <summary>
/// Edge in the network graph
/// </summary>
public class NetworkEdge
{
    public string Id { get; set; } = string.Empty;
    public string Source { get; set; } = string.Empty;
    public string Target { get; set; } = string.Empty;
    public string LinkType { get; set; } = string.Empty;
    public double Weight { get; set; }
    public bool IsAutoGenerated { get; set; }
}

/// <summary>
/// Interface for knowledge network service
/// </summary>
public interface IKnowledgeNetworkService
{
    Task<KnowledgeLink> CreateLinkAsync(int? userId, string sourceType, int sourceId, string targetType, int targetId, string linkType = "related", string? description = null);
    Task<bool> DeleteLinkAsync(int linkId, int? userId = null);
    Task<List<KnowledgeLink>> GetLinksForEntityAsync(string entityType, int entityId, int? userId = null);
    Task<List<RelatedContentItem>> FindRelatedContentAsync(string entityType, int entityId, int? userId = null, int maxResults = 20, int depth = 1);
    Task<int> GenerateSemanticLinksAsync(int? userId = null, double threshold = 0.85);
    Task<List<SearchResultItem>> SearchAsync(string query, int? userId = null, int maxResults = 20);
    Task<NetworkGraph> GetNetworkGraphAsync(int? userId = null, int maxNodes = 100);
    Task<bool> ConfirmLinkAsync(int linkId, int userId);
    Task<bool> RejectLinkAsync(int linkId, int userId);
    Task<List<KnowledgeLink>> GetPendingLinksAsync(int userId);
    Task<IndexingResult> IndexAllUserContentAsync(int userId);
    Task<ClusterVisualizationData> GetClusterVisualizationAsync(int userId, string method = "umap", int maxNodes = 200);
}

/// <summary>
/// Result of indexing operation
/// </summary>
public class IndexingResult
{
    public int DocumentsProcessed { get; set; }
    public int ExercisesProcessed { get; set; }
    public int KnowledgeItemsProcessed { get; set; }
    public int TotalProcessed { get; set; }
    public List<string> Errors { get; set; } = new();
}

/// <summary>
/// Cluster visualization data
/// </summary>
public class ClusterVisualizationData
{
    public bool Success { get; set; }
    public string? Message { get; set; }
    public string Method { get; set; } = "umap";
    public List<ClusterPoint> Points { get; set; } = new();
}

/// <summary>
/// Single point in cluster visualization
/// </summary>
public class ClusterPoint
{
    public string EntityType { get; set; } = string.Empty;
    public int EntityId { get; set; }
    public string Label { get; set; } = string.Empty;
    public double X { get; set; }
    public double Y { get; set; }
    public string Category { get; set; } = string.Empty;
}
