import 'package:freezed_annotation/freezed_annotation.dart';

part 'smart_reference_models.freezed.dart';
part 'smart_reference_models.g.dart';

/// Result of resolving smart references
@freezed
class SmartReferenceResult with _$SmartReferenceResult {
  const factory SmartReferenceResult({
    @Default([]) List<SmartReference> references,
    @Default(0.0) double overallConfidence,
    @Default(true) bool success,
    String? error,
    @Default(0) int processingTimeMs,
  }) = _SmartReferenceResult;

  factory SmartReferenceResult.fromJson(Map<String, dynamic> json) =>
      _$SmartReferenceResultFromJson(json);
}

/// A single smart reference
@freezed
class SmartReference with _$SmartReference {
  const factory SmartReference({
    @Default('') String originalText,
    @Default('event') String referenceType,
    ResolvedEntity? resolvedTo,
    @Default(0.0) double confidence,
    @Default(0) int startPosition,
    @Default(0) int endPosition,
  }) = _SmartReference;

  factory SmartReference.fromJson(Map<String, dynamic> json) =>
      _$SmartReferenceFromJson(json);
}

/// Information about a resolved entity
@freezed
class ResolvedEntity with _$ResolvedEntity {
  const factory ResolvedEntity({
    @Default('') String entityType,
    @Default(0) int entityId,
    @Default('') String displayName,
    @Default({}) Map<String, dynamic> metadata,
  }) = _ResolvedEntity;

  factory ResolvedEntity.fromJson(Map<String, dynamic> json) =>
      _$ResolvedEntityFromJson(json);
}

/// A suggested link between content and a resolved entity
@freezed
class SuggestedLink with _$SuggestedLink {
  const factory SuggestedLink({
    @Default('') String sourceType,
    @Default(0) int sourceId,
    @Default('') String targetType,
    @Default(0) int targetId,
    @Default('related') String linkType,
    @Default(0.0) double confidence,
    @Default('') String reason,
    String? referenceText,
    String? targetDisplayName,
  }) = _SuggestedLink;

  factory SuggestedLink.fromJson(Map<String, dynamic> json) =>
      _$SuggestedLinkFromJson(json);
}

/// Result of parsing temporal expressions
@freezed
class TemporalParseResult with _$TemporalParseResult {
  const factory TemporalParseResult({
    @Default(true) bool success,
    @Default([]) List<TemporalReference> references,
    String? error,
    @Default(0.0) double overallConfidence,
  }) = _TemporalParseResult;

  factory TemporalParseResult.fromJson(Map<String, dynamic> json) =>
      _$TemporalParseResultFromJson(json);
}

/// A parsed temporal reference
@freezed
class TemporalReference with _$TemporalReference {
  const factory TemporalReference({
    required DateTime resolvedStart,
    required DateTime resolvedEnd,
    @Default('') String originalExpression,
    @Default('contextual') String type,
    @Default(0.0) double confidence,
    @Default(0) int startPosition,
    @Default(0) int endPosition,
  }) = _TemporalReference;

  factory TemporalReference.fromJson(Map<String, dynamic> json) =>
      _$TemporalReferenceFromJson(json);
}

/// Professor information
@freezed
class ProfessorInfo with _$ProfessorInfo {
  const factory ProfessorInfo({
    @Default('') String name,
    @Default([]) List<String> variations,
    @Default([]) List<String> subjects,
    @Default([]) List<int> eventIds,
    int? mostRecentEventId,
  }) = _ProfessorInfo;

  factory ProfessorInfo.fromJson(Map<String, dynamic> json) =>
      _$ProfessorInfoFromJson(json);
}

/// Subject information
@freezed
class SubjectInfo with _$SubjectInfo {
  const factory SubjectInfo({
    @Default('') String name,
    String? courseCode,
    @Default([]) List<String> professors,
    @Default([]) List<int> eventIds,
  }) = _SubjectInfo;

  factory SubjectInfo.fromJson(Map<String, dynamic> json) =>
      _$SubjectInfoFromJson(json);
}

/// Knowledge link (simplified for Flutter)
@freezed
class KnowledgeLink with _$KnowledgeLink {
  const factory KnowledgeLink({
    required int id,
    int? userId,
    @Default('') String sourceType,
    @Default(0) int sourceId,
    @Default('') String targetType,
    @Default(0) int targetId,
    @Default('related') String linkType,
    @Default(1.0) double strength,
    @Default(false) bool isAutoGenerated,
    double? vectorSimilarity,
    String? description,
    @Default(true) bool isBidirectional,
    @Default(false) bool isConfirmed,
    @Default(false) bool isRejected,
  }) = _KnowledgeLink;

  factory KnowledgeLink.fromJson(Map<String, dynamic> json) =>
      _$KnowledgeLinkFromJson(json);
}
