using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DHBWAutomation.Backend.Core.Models;

/// <summary>
/// Explicit connections between knowledge items (the "Spinnennetz")
/// </summary>
[Table("knowledge_links")]
public class KnowledgeLink
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// User who owns this link (null = global/system link)
    /// </summary>
    public int? UserId { get; set; }

    // === Source Entity ===

    /// <summary>
    /// Source entity type: "document", "exercise", "knowledge_item", "image", "moodle_resource", "nextcloud_file"
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string SourceType { get; set; } = string.Empty;

    /// <summary>
    /// Source entity ID
    /// </summary>
    [Required]
    public int SourceId { get; set; }

    // === Target Entity ===

    /// <summary>
    /// Target entity type
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string TargetType { get; set; } = string.Empty;

    /// <summary>
    /// Target entity ID
    /// </summary>
    [Required]
    public int TargetId { get; set; }

    // === Link Metadata ===

    /// <summary>
    /// Link type: "related", "prerequisite", "extension", "example", "part_of", "derived_from", "duplicate"
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string LinkType { get; set; } = "related";

    /// <summary>
    /// Link strength/confidence (0.0 to 1.0)
    /// </summary>
    public double Strength { get; set; } = 1.0;

    /// <summary>
    /// Whether this link was auto-generated (via semantic similarity)
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Vector similarity score (if auto-generated)
    /// </summary>
    public double? VectorSimilarity { get; set; }

    /// <summary>
    /// Optional description of the relationship
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Whether this link is bidirectional
    /// </summary>
    public bool IsBidirectional { get; set; } = true;

    /// <summary>
    /// Whether the user has confirmed this auto-generated link
    /// </summary>
    public bool IsConfirmed { get; set; } = false;

    /// <summary>
    /// Whether the user has rejected this link (won't show again)
    /// </summary>
    public bool IsRejected { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    // Navigation
    [ForeignKey("UserId")]
    public virtual User? User { get; set; }
}

/// <summary>
/// Constants for link types
/// </summary>
public static class KnowledgeLinkTypes
{
    public const string Related = "related";
    public const string Prerequisite = "prerequisite";
    public const string Extension = "extension";
    public const string Example = "example";
    public const string PartOf = "part_of";
    public const string DerivedFrom = "derived_from";
    public const string Duplicate = "duplicate";
}

/// <summary>
/// Constants for entity types
/// </summary>
public static class KnowledgeEntityTypes
{
    public const string Document = "document";
    public const string Exercise = "exercise";
    public const string JavaDocsExercise = "java_docs_exercise";
    public const string KnowledgeItem = "knowledge_item";
    public const string Image = "image";
    public const string MoodleResource = "moodle_resource";
    public const string NextcloudFile = "nextcloud_file";
}
