using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DHBWAutomation.Backend.Core.Models;

/// <summary>
/// Defines prerequisite relationships between knowledge topics.
/// Enforces that foundational topics must be mastered before advanced ones.
/// </summary>
[Table("prerequisite_chains")]
public class PrerequisiteChain
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// The prerequisite knowledge node that must be mastered first.
    /// </summary>
    [Required]
    public int PrerequisiteNodeId { get; set; }

    /// <summary>
    /// The dependent knowledge node that requires the prerequisite.
    /// </summary>
    [Required]
    public int DependentNodeId { get; set; }

    /// <summary>
    /// Minimum mastery level required in the prerequisite (0.0 - 1.0).
    /// Default: 0.6 (60% mastery required).
    /// </summary>
    public double RequiredMasteryLevel { get; set; } = 0.6;

    /// <summary>
    /// If true, the prerequisite is strictly enforced (blocks progress).
    /// If false, only a warning is shown.
    /// </summary>
    public bool IsStrict { get; set; } = true;

    /// <summary>
    /// Human-readable description of the prerequisite relationship.
    /// Example: "Grundlagen Algebra -> Quadratische Gleichungen"
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Whether this prerequisite was auto-generated via semantic analysis.
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Confidence score for auto-generated prerequisites (0-1).
    /// </summary>
    public double? AutoGeneratedConfidence { get; set; }

    // Timestamps
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    [ForeignKey("PrerequisiteNodeId")]
    public virtual UserKnowledgeNode PrerequisiteNode { get; set; } = null!;

    [ForeignKey("DependentNodeId")]
    public virtual UserKnowledgeNode DependentNode { get; set; } = null!;
}

/// <summary>
/// Result of checking prerequisites for a knowledge node.
/// </summary>
public class PrerequisiteCheckResult
{
    /// <summary>
    /// Whether the user can proceed to this topic.
    /// </summary>
    public bool CanProceed { get; set; }

    /// <summary>
    /// Total number of prerequisites for this node.
    /// </summary>
    public int TotalPrerequisites { get; set; }

    /// <summary>
    /// Number of prerequisites that are met.
    /// </summary>
    public int MetPrerequisites { get; set; }

    /// <summary>
    /// List of missing prerequisites that block progress.
    /// </summary>
    public List<MissingPrerequisite> MissingPrerequisites { get; set; } = new();

    /// <summary>
    /// Human-readable reason if blocked.
    /// </summary>
    public string? BlockReason { get; set; }
}

/// <summary>
/// Details about a missing prerequisite.
/// </summary>
public class MissingPrerequisite
{
    public int NodeId { get; set; }
    public string Subject { get; set; } = string.Empty;
    public string Topic { get; set; } = string.Empty;
    public double CurrentMastery { get; set; }
    public double RequiredMastery { get; set; }
    public double MasteryGap => RequiredMastery - CurrentMastery;
    public double Gap => MasteryGap; // Alias for compatibility
    public bool IsStrict { get; set; }
}
